microsoft/mu_feature_mm_supv

MmSupervisorPkg/Docs/MmSupervisor_Feature.md
=> MmSupervisor_Feature.md: Fix PlatformIntegrationSteps.md link

MmSupervisorPkg/MmSupervisorPkg.ci.yaml, MmSupervisorPkg/MmSupervisorPkg.dsc, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/Acpi.c, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/Acpi.h, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/IVRS.h, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/IVRSTable.h, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmPolicyMeasurementLevels.h, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvMemPolicyUnitTest.c, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.c, MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.inf
This test will test fundamental MM requests and eventually validate the fetched MM security policy according to the Microsoft SCPC specification.
=> Added MM measurement UEFI shell unit test

ReadMe.rst
Updates the pipeline badge URLs for the new pipelines being used.
=> ReadMe.rst: Update CI badges for new pipelines

MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf, basecore_ext_dep.yaml, mu_plus_ext_dep.yaml, mu_tiano_ext_dep.yaml
Updates external repo dependencies for Project Mu repos to
include CodeQL fixes.
Note: A large number of reported issues are expected to be
fixed but not all will be fixed at this time.
=> Integrate Project Mu CodeQL fixes

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/MmSupervisorPkg.dec
This change bumps the version number to make a release before we transition to 202208.
=> Update package and module version

.azurepipelines/Ubuntu-GCC5.yml, .azurepipelines/Windows-VS.yml
- Triggers and schedules will be set in pipeline definitions
- Variable groups are used to centralize common settings
=> .azurepipelines: Use new Mu DevOps YAML design

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/MmSupervisorPkg.dec
This change only updated the version number to prepare for a new release, no firmware/functional changes.
Only version update. No functional change.
N/A
=> Bump up the version to v7.002 to prepare for new release

MmSupervisorPkg/Core/MmSupervisorCore.inf
Updates the tag do to recent CodeQL changes in PiSmmCpuDxeSmm.
The changes do not apply to code in MmSupervisorPkg.
- Examples: Unit tests, …
=> MmSupervisorCore: Update PiSmmCpuDxeSmm override tag

.pytool/CISettings.py, MmSupervisorPkg/Core/Services/MpService/MpService.c, MmSupervisorPkg/Drivers/StandaloneMmIpl/PiSmmIpl.c, MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.c, MmSupervisorPkg/Test/MmPagingAuditTest/UEFI/X64/PagingAuditProcessor.c, MmSupervisorPkg/Test/MmiHandlerProfileInfo/MmiHandlerProfileInfo.c
Fixing potential NULL pointer dereferences after allocation.
validation …
=> [CodeQL] MmSupervisorPkg: Fixing CodeQL failures in this package

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Refreshes override tags to fix the build.
- Examples: Unit tests, integration tests, robot tests, ...
- **Documentation** - Does the change …
=> MmSupervisorPkg: Update override tags

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/MmSupervisorPkg.dec
This change bumps the version number to make a release before we transition to 202302.
- Examples: Crypto algorithm change, buffer overflow …
=> Update package and module version to v8.001

MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
These libraries need to be linked against MmIplPei. Since they are
missing, linker failures can result depending on platform integration
of library instances against the module.
- **Tests** - Does the …
=> MmIplPei: Add missing libs to INF

MmSupervisorPkg/Core/Relocate/SmmInit.nasm, SpamPkg/MmiEntrySpam/MmiEntrySpam.nasmb
There are multiple `@LongMode` symbols in the pdb, while the tool can be updated to differentiate by specifying the origin of these source files, it is simpler to just update the name of these symbols from the supervisor.
- **Security** - …
=> Update nasm symbol names to make the specification easier

SpamPkg/Include/Library/PeCoffLibNegative.h
SpamBinBuild.py cannot successfully build without this bugfix.
- Examples: Unit tests, integration tests, robot tests, ...
- …
=> Add a ; to the newly defined KEY_SYMBOL struct

SpamPkg/Library/HashLibTpm2Raw/HashLibTpm2Raw.c, SpamPkg/Library/HashLibTpm2Raw/HashLibTpm2Raw.inf
This change added a base HashLib that will extend measurements into all active PCR banks. …
=> Add a raw HashLib instance that will extend into all active PCR banks

SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Adds MmiEntrySpam.bin and debug files to the spam artifacts.
- **Tests** - Does …
=> GenSpamArtifacts.py: Add MmiEntrySpam.bin and debug files

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/Core/Relocate/Relocate.c
The pipeline build is broken due to a commit cherry-picked in to basecore: https://github.com/microsoft/mu_basecore/commit/7f9a27e0d7bcefd06e8d45fc06d5e906b6898911.
This change is needed to unblock other PRs into this repo.
a function in a new library class in a …
=> Fixing override validation failure

MmSupervisorPkg/Core/Mem/PageTbl.c, SeaPkg/Core/Init/StmInit.c, SeaPkg/Core/Runtime/SeaResponderReport.c, SeaPkg/Core/Stm.inf, SeaPkg/SeaPkg.dsc
Making these available for others to have the same state and information.
Each of these commits can be individually reverted when the time comes.
- Build and boot
N/A
=> Temporary SEA Changes [Rebase & FF]

MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf, MmSupervisorPkg/Library/MmSupervisorMemLib/MmSupervisorMemLibSyscall.inf, MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.inf
Basecore updated StandaloneMmHobLib so the relevant tags need to be updated.
Tested on physical platform.  No issues seen.
N/A
=> Update override and tracking tags for StandaloneMmHobLib

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Updated Override tags to work with the latest MU_BASECORE release/202405 commit
Tested with CI
N/A
=> Updated BASECORE override tags

MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/MmSupervisorPkg.dec
Updates the major and minor version to match the current GitHub release version (14.0.2).
Verified version printed during boot.
N/A - No functional change.
=> MmSupervisorPkg: Update release version v14.002

MmSupervisorPkg/Core/Dispatcher/Dispatcher.c, MmSupervisorPkg/Core/MmSupervisorCore.inf, MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
This change cherry-picks the basecore update from https://github.com/microsoft/mu_basecore/commit/cd81b475a93d7b5c58b097b57d2057f54b21b9ad.
This change is tested on QEMU Q35 platfrom.
N/A
=> Fix override validation failure

MmSupervisorPkg/Core/Mem/HeapGuard.c
Change  heapguard global variables to CONST as they should never change.  This also will put them in the read only data which removes them as symbols that need a rule when using SEA.
Tested on an Intel physical platform.
N/A
=> Change  heapguard global variables to CONST

SeaPkg/Include/Library/PeCoffValidationLib.h, SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c, SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c, SeaPkg/Tools/GenSeaArtifacts/Cargo.toml, SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py, SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/bin/create_aux.rs, SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/bin/create_config.rs, SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/file.rs, SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/metadata.rs, SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs, SeaPkg/Tools/GenSeaArtifacts/test_aux/Cargo.toml, SeaPkg/Tools/GenSeaArtifacts/test_aux/README.md, SeaPkg/Tools/GenSeaArtifacts/test_aux/build.rs, SeaPkg/Tools/GenSeaArtifacts/test_aux/src/efi.rs, SeaPkg/Tools/GenSeaArtifacts/test_aux/src/main.rs
Gen Aux cherry-picks from main
N/A
N/A
=> [CHERRY-PICK][REBASE&FF] Aux Tooling Cherry-picks

MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
The current function does not consider V2 resource descriptor HOBs.
This change considers both V1 and V2 HOBs with V2 taking precedence if both are present.
- Boot platform with System Memory, MMIO, and Reserved resources described by V2 HOBs.
- Include this commit if V2 HOB support is needed for a platform.
=> MmSupervisorPkg/SmmCpuMemoryManagement: Add V2 resource descriptor HOB support

MmSupervisorPkg/Drivers/MmPeiLaunchers/MmDxeSupport.inf, MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
Update override tags targeting PiSmmIpl.inf
N/A
N/A
=> MmSupervisorPkg/MmPeiLaunchers: Update override tags

MmSupervisorPkg/Library/BaseLibSysCall/X64/GccInlinePriv.c
Align GCC-specific components of BaseLibSysCall to match SysCall replacements already made in MSFT components.
Executed `DisableInterrupts` and `AsmWriteMsr64` without triggering a General Protection fault.
N/A
=> BaseLibSysCall: Support GCC build family
