microsoft/mu_feature_mm_supv

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/MmSupervisorPkg.dec
This change updated the package and core module inf versions to make it align with the Pe/Coff image version of supervisor.
> Aligning version strings for core module and package

- MmSupervisorPkg/Core/Handler/SmiHandlerProfile.c
ConvertSmiHandlerSwContext() is called by SmiHandlerProfileRegisterHandler() which is called by ProcessUserHandlerReg() when the supervisor dispatcher handles a SMM_MM_HDL_REG_1/SMM_MM_HDL_REG_2 request to register a child SMI handler with a gEfiSmmSwDispatch2ProtocolGuid handler guid. ConvertSmiHandlerSwContext() is handed a user space provided context and context size, and it will convert an EFI_SMM_SW_REGISTER_CONTEXT structure to a SMI_HANDLER_PROFILE_SW_REGISTER_CONTEXT structure. It doesn't check the context size and simply assumes it's large enough to hold the data it needs (it only does an assert). This could lead to user space inducing the supervisor to touch supervisor pages and possibly info leak some supervisor page data (a couple of bytes).
However, this is a debug feature …
> Fixed missing length check in ConvertSmiHandlerSwContext()

- MmSupervisorPkg/Core/Hand/Handle.c
- MmSupervisorPkg/Core/Handler/SmiHandlerProfile.c
SmiHandlerProfileUnregisterHandler() is called by ProcessUserHandlerUnreg() which is called by the supervisor when handling SMM_MM_HDL_UNREG_1/SMM_MM_HDL_UNREG_2 syscalls. It takes a guid pointer (as well as a context and context size) provided by user space. It has been inspected with a call to InspectTargetRangeOwnership() to ensure it belongs to user space. SmiHandlerProfileUnregisterHandler() uses the guid pointer twice. Once to look up the handler (and its associated context) and a second time to free memory if the guid content is the same as gEfiSmmUsbDispatch2ProtocolGuid.
Given that the guid points to user space controlled data, it is possible that this content could have changed between the first time it was used and the second time it was used. I'm not sure if …
> Fixed GUID comparison that could lead to arbitrary write from FreePool()

- MmSupervisorPkg/Core/Handler/Mmi.c
- MmSupervisorPkg/Core/MmSupervisorCore.c
- MmSupervisorPkg/Core/MmSupervisorCore.h
- MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
The supervisor handles syscalls to register and unregister handlers on user space's behalf by exposing a SMM_REG_HNDL and SMM_UNREG_HNDL syscall. for registration it calls MmiUserHandlerRegister() to do this work, which calls CoreMmiHandlerRegister() with IsSupervisorHandler set to FALSE. For unregistering, it calls MmiHandlerUnRegister() with a user-provided handle. It performs a handle lookup and, if found, unregisters the handler. MmiHandlerUnRegister() makes no effort to see whether the handler's IsSupervisor BOOLEAN is set or not. In order words, a user-space caller can unregister a supervisor-created handler.
The impact of unregistering supervisor handler could potentially miss some events and potentially lose capability of reporting secure policy. However, security …
> Fixed SMM_UNREG_HNDL can unregister any handler, including supervisor ones

- MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
The supervisor handles the SMM_START_AP_PROC call index. It calls the gMmCoreMmst.MmStartupThisAp() function pointer with 3 arguments provided by userspace. The exact function pointer points to SmmStartupThisAp().
The second argument (Arg2) is seen as a CpuIndex and is used as an index into an array that is being written too. There are no bounds checks to ensure the index is <= the number of CPUs present. In this case, user-space gets to provide an unvalidated index and write user-controlled values almost anywhere in memory.
Fix:
Add CpuIndex validation inside the dispatcher when handling SMM_START_AP_PROC.
fixes #10
> Fixed unvalidated CpuIndex (Arg2) in SMM_START_AP_PROC can cause out of bound writes

- MmSupervisorPkg/Core/PrivilegeMgmt/SysCallEntry.nasm
SyscallCenter implemented in SysCallEntry.nasm is called as the supervisor entry point when user space issues a SYSCALL instruction. This function is responsible for proper setup, calling the dispatcher, and then returning to user space properly.
Except, it doesn't seem to restore all registers. It restores a subset of the general purpose registers (r11, rbx, rdi, r12, rsi, r9, r8, rdx, rbp rcx and rsp), clearly leaving out r10, r13, r14, and r15. If the dispatcher uses any of these registers, they would get returned to user space.
In addition to the general purpose registers, it doesn't seem to restore any of the FPU/MMX/SSE/AVX registers. Optimizing compilers tend to use the SIMD registers and instructions for things like memcpy().
Fix:
In the syscall interface:
- …
> Syscall entry/exit register save / restore (general purpose and FPU/MMX/SSE/AVX)

- MmSupervisorPkg/Core/Mem/Page.c
- MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
The supervisor calls MmFreePages() to free pages previously allocated with a call to SMM_ALOC_PAGE. In the SMM_ALOC_PAGE case, a call is made to MmAllocatePages(), which eventually lands inside of MmInternalAllocatePagesEx(), which makes sure the number of pages provided by user space can't be too large (no more than 48 bits essentially, as any more pages would require more memory than the 64-bit address space would logically allow for). This check makes a lot of sense.
Unfortunately, MmAllocatePages()'s counterpart, MmFreePages() has no such check. The number of pages provided by userland callers can be > 48 bits big. When converted to actual size (using the EFI_PAGES_TO_SIZE() macro), an integer overflow can lead the code to believe that fewer pages than required are …
> MmFreePages() doesn't properly check NumberOfPages

- MmSupervisorPkg/Core/Misc/InstallConfigurationTable.c
MmInstallConfigurationTable() is called by the supervisor to allow user space to install configuration tables. It looks up the guid, and if it can't find it in the current table, it adds an entry. If there is no room left in the tables, they get reallocated to account for extra space. This reallocation has an interesting logic error. It updates the global variable (mMmSystemTableAllocateSize) that holds the table's max size prior to allocation. If the allocation fails (and hence no reallocation occurs), the global size variable isn't reset. This means the next caller that wants to add an entry would trigger memory corruption.
This has the potential for a compromised SMM handler to break into the supervisor, assuming a full memory corruption exploit. One of the …
> Fixed global length field updated even allocation in MmInstallConfigurationTable() failed

- MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c
- MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.inf
- MmSupervisorPkg/Library/SmmPolicyGateLib/UnitTest/SmmPolicyGateLibUnitTest.c
- MmSupervisorPkg/Library/SmmPolicyGateLib/UnitTest/SmmPolicyGateLibUnitTest.inf
- MmSupervisorPkg/MmSupervisorPkg.ci.yaml
- MmSupervisorPkg/Test/MmSupervisorPkgHostTest.dsc
The supervisor calls IsIoReadWriteAllowed() to see if a user can read or write to specific io ports. The code looks pretty decent; however, a few minor things seem wrong. There's some weirdness around casting and truncating when calling it (and when later using the ioports), which looks kinda bad, but ultimately it doesn't seem to cause many problems.
When validating the ioport and size, there is an integer overflow. It will overflow if the port is really big (0xfffffffd or larger). If there is a policy to allow writes to low ports (e.g., 0), then it could allow writing to a high port (e.g., 65535, 0xffffffff truncated to 16 bits). Ultimately this is a really specific set of circumstances and probably not that big of a deal, but it does look like a clear bug that should …
> Fix integer overflow in IsIoReadWriteAllowed()

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/MmSupervisorPkg.dec
BASECORE recently moved to `CONSOLE` as subsystem during linking process, in order to support NX flag.
However, the side effect of this change is enforcing the subsystem level to be 5.0* at minimum, according to this document:
https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170#remarks
This change updated the subsystem level to be 6.02* to be higher than the default value.
Patch level is also updated to reflect that the security patches applied from last refresh.
> Updated the version number since we moved to console build to support NX

- MmSupervisorPkg/Core/Mem/Page.c
This change fixed a potential overflow where if the maximal allowed number of pages being passed in (0x10000), the return will be an address of 0 pages.
The security impact is minimal as on allocation, the returned address will be either pointing to a free page that is marked with supervisor privilege or guarded page with read prevention protection. On the freeing, the input address will fail the internal attribute look up and bail early.
> Fixing an edge case of incoming parameter check

- .azurepipelines/Ubuntu-GCC5.yml
- .azurepipelines/Windows-VS.yml
Prior to using Mu DevOps, this repo did not use Stuart PR Evaluation.
.pytool/CISettings.py does not implement a PrEvalSettingsManager.
To maintain this configuration, this change opts the YAML files in
the repo out of PR evaluation in the templates used for build in
Mu DevOps.
> .azurepipelines: Opt out of PR Evaluation

- .github/workflows/codeql-analysis.yml
Updates codeql-analysis.yml to use a common reusable workflow from
mu_devops for CodeQL analysis.
> codeql-analysis.yml: Use Mu Devops CodeQL workflow

- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
- MmSupervisorPkg/Test/MmiHandlerProfileInfo/MmiHandlerProfileInfo.inf
- basecore_ext_dep.yaml
- pip-requirements.txt
Updates mu_basecore to the latest commit so consuming packages that
need to move to latest can get the latest override validation track
tags needed.
Adds "regex" to pip-requirements.txt as it is needed by the DebugMacroCheck
plugin picked up in this mu_basecore update.
> basecore_ext_dep.yaml: Update to latest mu_basecore (4d60e12)

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- basecore_ext_dep.yaml
- mu_plus_ext_dep.yaml
- mu_tiano_ext_dep.yaml
Updated dependencies to be top of tree so that platforms relying on this repo don't run into tracking errors.
> Updated dependencies to latest

- MmSupervisorPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
Removes a link in markdown that is causing a markdown lint failure. Required to complete containerized build. https://github.com/microsoft/mu_feature_mm_supv/pull/49
N/A
N/A
> Remove broken link in PlatformIntegrationSteps.md

- MmSupervisorPkg/Core/Dispatcher/Dispatcher.c
- MmSupervisorPkg/Core/MmSupervisorCore.h
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
- MmSupervisorPkg/MmSupervisorPkg.ci.yaml
- MmSupervisorPkg/MmSupervisorPkg.dsc
- MmSupervisorPkg/Test/MmPagingAuditTest/UEFI/MmPagingAuditApp.inf
- MmSupervisorPkg/Test/MmPagingAuditTest/UEFI/X64/PagingAuditProcessor.c
- basecore_ext_dep.yaml
- mu_plus_ext_dep.yaml
- mu_tiano_ext_dep.yaml
This change added the support for stack cookie in standalone MM core and user modules:
- Added assembly function to write to `ICC_SGI1R` from non-secure EL1/EL2
- Extended current `ArmGicSendSgiTo` interface to also support sending SGI on GIC v3 and v4
- Added a new PSCI command index to query PSCI suspend features.
The assembly support is intentionally left out as the common solution for MSVC and GCC
support is still under development.
Tested on both GCC and MSVC compiled Q35 platform.
Need to include the appropriate instance of `BaseBinSecurityLib` in the platform dsc file to pass the build.
> [Rebase & FF] Add stack cookie

- MmSupervisorPkg/Core/Mem/PageTbl.c
- MmSupervisorPkg/Drivers/MmCommunicationBuffer/MmCommunicationBufferDxe.c
- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.c
Makes changes to comply with alerts raised by CodeQL.
A prior pass with a subset of queries used here was already done so this is mostly addressing
issues discovered by enabling a few new queries.
Most of the issues here fall into the following two categories:
1. Potential use of uninitialized pointer
2. Inconsistent integer width used in loop comparison
- Will this change break pre-existing builds or functionality without action being taken?
**No** - Should just be refactoring to address alerts
1. Verified CI build
N/A
> CodeQL Fixes - Second Pass

- MmSupervisorPkg/Core/PrivilegeMgmt/AsmCallGateTransfer.nasm
- MmSupervisorPkg/Core/PrivilegeMgmt/CallGateTransfer.c
- MmSupervisorPkg/Core/PrivilegeMgmt/PrivilegeMgmt.h
- MmSupervisorPkg/Core/PrivilegeMgmt/SysCallEntry.nasm
- MmSupervisorPkg/Drivers/MmSupervisorErrorReport/AsmErrorReportRing3JumpPointer.nasm
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/Handler/AsmStandaloneRing3JumpPointer.nasm
- MmSupervisorPkg/Library/StandaloneMmDriverEntryPoint/AsmStandaloneMmDriverEntryPoint.nasm
In the original implementation, each operation privilege transitioning has its own function, which is mostly alike, causing the same change having to be replicated four times each change involving these routines..
This change mainly converges the 4 routines into a general-purpose assembly routine `InvokeDemotedRoutine`, which accepts variable input arguments and transition them into desired function, for both BSP and AP procedures.
In the meantime, this change also fixes stack alignment discrepancy when the …
> Converge demotion routines in assembly into one and update the stack alignments

- MmSupervisorPkg/Core/PrivilegeMgmt/AsmCallGateTransfer.nasm
The existing routine does not reserve enough number of stack segment before calling into other C functions (more information can be seen [here](https://learn.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-170#stack-allocation)), which could cause the reserved memory on the stack to be corrupted and consumed.
This change allocated enough parameter space on the stack before calling into other functions and unwind the displacement after returning.
For each item, place an "x" in between `[` and `]` if true. …
> Fixed stack corruption issues with assembly routine

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.inf
Tags need to be updated when building against the latest mu_basecore
due to this change in StandaloneMmPkg:
https://github.com/microsoft/mu_basecore/commit/5f8c0d90fbf0dbfcefb88a0cca5331f44cb2376f
- …
> MmSupervisorPkg: Update StandaloneMmPkg override tags

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.inf
Hashes needed to build against latest changes.
- Examples: Unit tests, integration tests, robot tests, ...
- **Documentation** - Does the …
> MmSupervisorPkg: Update secure override hashes

- .pytool/CISettings.py
Updates the CodeQL file filter list to include all filters found in
the repo. This will pick up filters from repos like mu_basecore.
- …
> .pytool/CISettings.py: Use all CodeQL filter files

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
- MmSupervisorPkg/MmSupervisorPkg.dec
Resolves #99 
This change will introduce a new PCD to untangle the syscall entry logging from verbose level. Per feedback from this issue: https://github.com/microsoft/mu_feature_mm_supv/issues/99, the logging is too intrusive to allow the system booting reasonably.
The newly introduced PCD will disable the logging by default to allow system to continue using verbose without further negatively impacting the booting process.
flow, or …
> Untangle syscall entry logging using feature PCD

- MmSupervisorPkg/Core/Dispatcher/Dispatcher.c
The message that prints the security cookie value initialized during
PE image load prints in total about 150 times on some Intel platforms
(depending on DXE/MM module count and cookie config settings).
This information is typically not needed unless specialized debug
related to security cookies is required which is rare. This change
constrains the message to `DEBUG_VERBOSE` (instead of `DEBUG_INFO`)
in addition to `DEBUG_LOAD`.
- **Breaking …
> MmSupervisorPkg/Core: Reduce stack cookie value verbosity

- MmSupervisorPkg/MmSupervisorPkg.ci.yaml
Add a PrEval entry to all ci.yaml files. This enables the PrEval Policy 5
- Examples: Unit tests, integration tests, robot tests, ...
- …
> ci.yaml: add PrEval entry

- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvMemPolicyUnitTest.c
- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.c
Updates the `UT_LOG_*` messages to print a new line so the prints
do not run into the individual test section dividers.
Prints additional information when examining IOMMU regions to show
what regions are being considered and specific details about
potential range overlaps.
- Examples: Add a new library class, move a module to a different …
> MmSupvervisorPkg/MmSupvRequestUnitTestApp: Add debug info

- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvMemPolicyUnitTest.c
This change updated the unit test to inspect retrieved MM policy attribute against protected regions, such as TXT and IOMMU regions as defined by WHCP specification.
Although the specification only mentions that the regions should have no write access, this implementation will flag attributes on executable protected regions.
- **Functionality** - Does the change ultimately impact how firmware …
> Evaluate protected regions with proper memory attribute checks

- MmSupervisorPkg/SupervisorPolicyTools/policy_entry.py
- MmSupervisorPkg/Test/MmPagingAuditTest/Windows/MemoryRangeObjects.py
Catching a bare exception is considered bad practice.  Catching bare exceptions can make it impossible to interrupt the program (e.g., with Ctrl-C) and can disguise other problems.  This removes all bare excepts and instead catches `Exception` which is the base class for all code-generated exceptions.
- Examples: Add a new library class, …
> MmSupervisorPkg: Remove bare excepts

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmDxeSupport.inf
- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
- MmSupervisorPkg/Drivers/StandaloneMmIpl/PiSmmIpl.c
- MmSupervisorPkg/Drivers/StandaloneMmIpl/PiSmmIpl.inf
Updates overrides for:
- MdeModulePkg/Core/PiSmmCore/PiSmmIpl.inf
- UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf
Relevant changes from https://github.com/microsoft/mu_basecore/pull/490
- **Tests** - …
> Update overrides for recent Mu Basecore CodeQL fixes

- MmSupervisorPkg/Core/PrivilegeMgmt/SyscallDispatcher.c
Current implementation of `MmIsBufferOutsideMmValid` for the user instance will only check to see if the requested space is unblocked from the perspective of MM supervisor, which could result in the issue that the region is only unblocked at the supervisor level is still not accessible from user space. If this is the case, `FALSE` should be returned.
in build or boot …
> Adding extra step of ownership inspcetion for buffer validity check

- MmSupervisorPkg/MmSupervisorPkg.dec
`PcdUserCommBufferPages` is currently set to `4`. This buffer is
used for UEFI variable transactions where includes larger data like Intel
memory training and Secure Boot related UEFI variables.
16 pages provides 64KB by default which allows these common scenarios
to succeed in most cases without platform intervention.
- Examples: Add a new …
> MmSupervisorPkg.dec: Use 16 pages for user mode comm buffer by default

- MmSupervisorPkg/Core/Mem/SmmProfileInternal.h
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Core/Relocate/Relocate.h
- MmSupervisorPkg/Core/Test/PagingAudit.c
- MmSupervisorPkg/Library/BaseCpuLibSysCall/BaseCpuLib.inf
- MmSupervisorPkg/MmSupervisorPkg.dsc
- MmSupervisorPkg/Test/MmPagingAuditTest/UEFI/MmPagingAuditApp.inf
- MmSupervisorPkg/Test/MmPagingAuditTest/UEFI/X64/PagingAuditProcessor.c
- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvMemPolicyUnitTest.c
- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.c
- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.inf
Updates the repo for a change that merged UefiCpuLib with CpuLib.
UefiCpuLib will be removed entirely soon so all references are updated to CpuLib.
- **Tests** - Does the change include any explicit …
> MmSupervisorPkg: Integrate UefiCpuLib breaking change

- MmSupervisorPkg/Core/MmSupervisorCore.h
- MmSupervisorPkg/Core/Request/RequestDispatcher.c
Fixes #182 
The main change is to remove a NULL check for the CommBufferSize
parameter value in the MM_SUPERVISOR_REQUEST_FETCH_POLICY switch
case since it triggers a CodeQL alert as a redundant NULL check
operation. The actual parameter value is checked for NULL at the
beginning of the function and not modified until that line of code.
However, the function API and implementation is confusing so that's
cleaned up as well.
1. The Context parameter is not used at all. Since it is marked
optional, it is left so the function prototype can remain
consistent in case the parameter is needed in the future.
2. The CommBuffer and CommBufferSize parameters are also marked
optional, but they're not. The function immediately returns
EFI_INVALID_PARAMETER if they are not provided (null).
For (2), the …
> MmSupervisorPkg/Core: Remove redundant null check (CodeQL)

- MmSupervisorPkg/Core/Dispatcher/Dispatcher.c
- MmSupervisorPkg/Core/MmSupervisorCore.h
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- MmSupervisorPkg/MmSupervisorPkg.dsc
This series transitions the core to use the new stack cookie libraries.
The stack cookie value no longer needs to be initialized before
image execution and can instead be initialized in the library
constructor. 
a function in a new library class in a pre-existing …
> Use New Stack Cookie Library

- .git-blame-ignore-revs
Adds commits that only converted line endings to a
.git-blame-ignore-revs file so they are ignored by git blame. This is
supported by GitHub:
https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
This helps clean up git blame by filtering out these changes.
Note: This file needs to be updated on rebase branches. Processes
like filter-branch can automatically update relevant SHAs.
- **Breaking change** - Will anyone …
> .git-blame-ignore-revs: Ignore Line Ending only commits

- MmSupervisorPkg/Core/Dispatcher/Dependency.c
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- Derived from edk2 commit: 2ddae5df31789853040f4c5261bb85e2f010c4a7
- Override hash updated to reflect change in mu_basecore
The current dependency evaluator violates the memory access permission
when patching depex grammar directly in the read-only depex memory area.
Laszlo pointed out the optimization issue in the thread (1) "Memory
Attribute for depex section" and provided suggested patch to remove the
perf optimization.
In my testing, removing the optimization does not make significant perf
reduction. That makes sense that StandaloneMM dispatcher only searches
in MM protocol database and does not depend on UEFI/DXE protocol
database. Also, we don't have many protocols in StandaloneMM like
UEFI/DXE.
From Laszlo,
> "The patch removes the EFI_DEP_REPLACE_TRUE handling altogether, plus …
> MmSupervisorPkg/Core: Remove optimization for depex evaluation

- MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
- MmSupervisorPkg/Library/StandaloneMmHobLibSyscall/StandaloneMmHobLibSyscall.c
Contains the primary commit for the HOB calculation overflow and
a separate commit to build with the tip of mu_basecore release/202302.
---
**CVE-2022-36765 - StandaloneMmHobLibSysCall: Prevent integer overflow in CreateHob()**
Based on commit `9a75b030cf27d2530444e9a2f9f11867f79bf679` in edk2.
>  REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4166
>  Fix integer overflow in various CreateHob instances.
>  Fixes: CVE-2022-36765
>  The CreateHob() function aligns the requested size to 8
>  performing the following operation:
>  ```
>  HobLength = (UINT16)((HobLength + 0x7) & (~0x7));
>  ```
>  No checks are performed to ensure this value doesn't
>  overflow, and could lead to CreateHob() returning a smaller
>  HOB than requested, which could lead to OOB HOB accesses.
--- …
> CVE-2022-36765 - StandaloneMmHobLibSysCall: Prevent integer overflow in CreateHob() [Rebase & FF]

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/MmSupervisorPkg.dec
This change updated the release version to v9 to reflect the new value from release template.
- Examples: Unit tests, integration tests, …
> Bump version value to v9 to match the release version

- SpamPkg/Library/SmmCpuFeaturesLib/CpuFeaturesLib.h
- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
- SpamPkg/Library/SmmCpuFeaturesLib/StandaloneMmCpuFeaturesLib.c
This change should fix the constructor not invoking the proper STM based constructor.
- Examples: Crypto algorithm change, buffer overflow …
> This should fix the constructor not calling the real stm constructor

- SpamPkg/Plugins/TestPlugin/GenAux.py
This change removes the size of 4 bytes manipulation. from the aux file generation script. …
> Remove temporary fix for the size mismatch

- MmSupervisorPkg/MmSupervisorPkg.dsc
An instance of StackCheckLib must be in each DSC to accommodate -fstack-protector and /GS flags.
- Examples: Unit tests, integration tests, …
> Add StackCheckLib Instances to Platform DSC Files

- SpamPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
Current implementation is mis-calculating the offset for the case of non-zero type validation, this will cause compromised data returned.
- …
> Fixing offset for non-zero case

- SpamPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
This change fixed issues with validation of content and self-reference types.
This change also added more logs for debugging purpose.
- …
> Fix content and self-reference validation

- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
The MMI entry size is updated incorrectly after the section size is populated, causing the patching offset calculation pointing to the middle of nowhere. …
> Fixing the MMI entry size updated incorrectly

- pip-requirements.txt
It does not seem that the edk2-basetools are not being used. This change will remove it. …
> Remove basetools dependencies

- SpamPkg/Include/Library/PeCoffLibNegative.h
- SpamPkg/Tools/gen_aux/readme.md
- SpamPkg/Tools/gen_aux/src/auxgen.rs
- SpamPkg/Tools/gen_aux/src/main.rs
Adds two additional fields to `IMAGE_VALIDATION_DATA_HEADER`, `KeySymbolCount` and `OffsetToFirstKeySymbol` and a new struct, `KEY_SYMBOL` which is a U32, U32 (Signature / Offset) pair. 
Updates the aux gen to support adding key symbols via the config file by using the `[[key]]` config header.
This will allow a consumer of the auxillary file to define a set of key symbols that are necessary before performing any validation of an efi. The expectation is that the signature will allow the consumer to identify the purpose of the provided offset and act accordingly. The expectation is not that the signature will match the symbol name, but the purpose that the symbol is used for.
```
+--------------------------------------------+
+  IMAGE_VALIDATION_DATA_HEADER …
```
> Add key symbols to the auxillary file

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Core/Relocate/Relocate.h
- MmSupervisorPkg/Core/Services/MpService/MpService.c
- MmSupervisorPkg/Core/Services/MpService/MpService.h
- MmSupervisorPkg/Library/StandaloneMmCpuSyncLib/StandaloneMmCpuSyncLib.c
- MmSupervisorPkg/Library/StandaloneMmCpuSyncLib/StandaloneMmCpuSyncLib.inf
- MmSupervisorPkg/MmSupervisorPkg.dsc
Integrated the following commits from MU_BASECORE into the supervisor core (which themselves were taken from edk2):
https://github.com/microsoft/mu_basecore/commit/fba09d01a35746f4e8a3b03a70b1f13fb43342be
https://github.com/microsoft/mu_basecore/commit/f5417b804d5cb89dbbe384458fa6dfc0b81377ff
https://github.com/microsoft/mu_basecore/commit/d421e2b9c9d1af511aca95a20f6fe483f646909b
https://github.com/microsoft/mu_basecore/commit/bb7120572e7f8754fa46aaf01b76f9734ab4b29e
Additionally updated the override of UefiCpuPkg in the supervisor cores inf.
flow, or …
> Add SmmCpuSyncLib to the mm supervisor core

- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
- SpamPkg/MmiEntrySpam/MmiEntrySpam.nasmb
The existing nasmb code has various issues that cannot launch SMM properly.
This change fixed both the assembly code that can bring the system into x64 mode, as well as fixing the fixup logic from the initialization code to patch the appropriate content into the MMI entry routine.
- Examples: Add a new library, …
> Fix MMI entrypoint code for standalone binary integration

- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
The IDTr is incorrect using the IDT base. This change fixed the IDT usage and updated the check for newly supplied IDTr values.
A build fix is also added to fix the error from the last nasmb fix.
- **Security** - Does the change have a …
> Fix IDTr for the standalone MMI entry binary

- MmSupervisorPkg/Core/Misc/SmmFuncsArch.c
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Core/Telemetry/Telemetry.c
- MmSupervisorPkg/MmSupervisorPkg.dec
The current exception handling routine has 2 issues:
1. When it comes to page fault, the miscellaneous exception handler will print the exception context and then hand off to the specific page fault handler, which will make the log appear as the system double fault.
2. When the page fault exception occurs, the existing setup will switch the system to use a separate stack, which is hardcoded to be 4KB from the top of supervisor stack. This size is insufficient after switching to PageTableLib based page table …
> Fix exception handling errors for supervisor

- SpamPkg/Include/SpamResponder.h
- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
- SpamPkg/MmiEntrySpam/MmiEntrySpam.nasmb
This change updated the macro definition name according to the patched symbol name.
This is a non-functional change.
- Examples: Crypto …
> Update Macro definition name as the patch name changes.

- MmSupervisorPkg/Core/Mem/SmmProfile.c
- MmSupervisorPkg/Core/Relocate/Relocate.c
The system will not patch the SMI entry during initialization if the default SMI entry will not be used.
- Examples: Crypto algorithm …
> Remove code patching when not using the default SMI entry

- SpamPkg/Tools/gen_aux/readme.md
- SpamPkg/Tools/gen_aux/src/auxgen.rs
- SpamPkg/Tools/gen_aux/src/main.rs
Updates the config file to accept a [char; 4] instead of a u32 for the key symbol signature. This is to better match the SIGNATURE_32 function provided by edk2, which converts 4 characters into a u32 signature.
a function in a new library class in a pre-existing …
> aux_gen: Update key symbol signature format

- SpamPkg/Tools/GenSpamArtifacts/GenSpamArtifacts.py
Python 3.10 and 3.11 do not support nested double quotes in f-strings. Replaces the nested double quote with a single quote.
- Examples: …
> GenSpamArtifacts.py: Support Python 3.10, 3.11

- MmSupervisorPkg/Core/MmSupervisorCore.c
- SpamPkg/Core/Runtime/SpamResponderReport.c
- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
After updating the SPAM responder data definition, the C code in SmmStm.c is not updated accordingly.
This change fixed the torn state issue by correctly populating the data fields.
- **Security** - Does the change have a direct security …
> Fix SPAM responder data in a torn state

- MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
- MmSupervisorPkg/Core/Misc/MemoryAttributesTable.c
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- MmSupervisorPkg/MmSupervisorPkg.dsc
This change integrates 4 commits from MU_BASECORE to use the common library implementation for image record creation and resolve the corresponding override validation failures.
- **Security** - Does the change have a direct security impact …
> Integrate image record changes from MU_BASECORE

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/MmSupervisorPkg.dec
We have not updated this field for too long, which will make the print out during runtime have discrepancy compared to the code release version. This change is made to fix that.
- **Tests** - Does the …
> Update release version to v11 to match release versioning

- SpamPkg/Core/Runtime/SmmEptHandler.c
- SpamPkg/Core/Runtime/SpamResponderUtilities.c
- SpamPkg/Library/SmmCpuFeaturesLib/SmmStm.c
- SpamPkg/MmiEntrySpam/MmiEntrySpam.nasmb
The values used for the various DSC offsets in MmiEntrySpam.nasmb were based on the normal SmiEntry.nasm used in the MM Supervisor.  Instead, the needed to align with the STM file structure.  This change changes the offsets to correctly match the structure they're referencing when pulling variable data.
Additionally, SmmStm.c was updated to reference mXdSupported instead of gPatchDxSupported.  This also included a check for setting gPatchMsrIa32MiscEnableSupported based on the return value of StandardSignatureIsAuthenticAMD().
Also 2 files in the spam core had uncrustified run on them to pass CI.
- **Functionality** - Does the change ultimately impact how firmware …
> Fix Dsc offsets in MmiEntrySpam.nasmb

- MmSupervisorPkg/Core/Request/FetchPolicy.c
- MmSupervisorPkg/Include/Library/SecurePolicyLib.h
- MmSupervisorPkg/Library/SecurePolicyLib/MemPolicy.c
- SpamPkg/Core/Runtime/SpamResponderReport.c
This change added the input argument of page table when walking through the page table.
This will allow the SPAM core and supervisor core to walk through page tables at the same address.
- **Security** - Does the change have a direct …
> Expand common secure policy library to accept page table address as input

- MmSupervisorPkg/Core/Services/MpService/MpService.c
Primarily made to pull in this change [`UefiCpuPkg/PiSmmCpuDxeSmm: Use NonSmm BSP as default SMM BSP.`](https://github.com/tianocore/edk2/commit/68d506e0d15c0c412142be68ed006c65b641560f).
Also includes other optimizations to keep the file in sync with edk2. The history of the recent changes in the file in this repo vs edk2 are shown for reference.
| Commit URL                                                                                             | Title                                             | Notes                                                                            |
|--------------------------------------------------------------------------------------------------------|----------------------------------------------------|------------------------------------------------- …
> Port Recent MpService Changes [Rebase & FF]

- MmSupervisorPkg/Test/MmSupvRequestUnitTestApp/MmSupvRequestUnitTestApp.c
This change fixes a code path where the Status could get evaluated without being initialized. …
> Fix uninitialized variables for CLANG

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Core/Relocate/Relocate.c
This change is integrating the changes from BASECORE:
https://github.com/microsoft/mu_basecore/commit/ff7dabfdca8534a1d1b3551e91b739be20a5f8fc
https://github.com/microsoft/mu_basecore/commit/719bf756ea6d94ef800eaab4601d3ed52423ef35
- …
> Fixing override break due to PiSmmCpuDxeSmm updates

- MmSupervisorPkg/Core/MmSupervisorCore.inf
PiSmmCpuDxeSmm was updated to use Panic library and Panic calls instead of CPU_DEADLOOPs for error conditions.
This changed the generated override validation tag. mu_feature_mm_supv needed updated.
The consumption of PanicLib was not introduced at this time. Details can be seen at link below:
 
https://github.com/microsoft/mu_basecore/commit/bbbff00dc39a67dc1e44aa0ce392d460b12f66b9
- **Breaking change** - Will anyone consuming this change …
> Fixing override break due to PiSmmCpuDxeSmm updates.

- MmSupervisorPkg/Core/Mem/Mem.h
- MmSupervisorPkg/Core/Mem/PageTbl.c
- MmSupervisorPkg/Core/Mem/SmmCpuMemoryManagement.c
Updated AllocatePageTableMemory to include a new input variable *NewAllocation.  This variable is used to keep track of if new pages were allocated for use in the page table page pool.  This fixes a bug where if we run out of page table pool pages while changing some pages memory attributes we'll recursively call into ConvertMemoryPageAttributes while allocating pages leading to unaccounted for pages in the original call.  This leads to an assert by the ConvertMemoryPageAttributes code. …
> Changed AllocatePageTableMemory to include a new variable

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
- MmSupervisorPkg/MmSupervisorPkg.dec
This change updates the version information of this package and module. It also updates the document on how to integrate the latest changes into platforms that are picking up 202405.
The version number is updated from `11` to `13` to match the release version, which was missed in v12 release.
- Examples: Add a new library class, move a …
> Document update and version change

- SeaPkg/Core/Init/StmInit.c
Prevent dereference of the `Register` parameter if the argument is NULL.
- Build and boot
- N/A
> StmInit: Validate SeaVmcallDispatcher() parameter

- MmSupervisorPkg/Core/Mem/Page.c
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Core/Services/MpService/MpService.c
- MmSupervisorPkg/Core/Services/MpService/MpService.h
- MmSupervisorPkg/Core/Services/MpService/SyncTimer.c
- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmDxeSupport.inf
- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
- MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
- MmSupervisorPkg/Library/BaseLibSysCall/String.c
- MmSupervisorPkg/Test/MmiHandlerProfileInfo/MmiHandlerProfileInfo.c
- MmSupervisorPkg/Test/MmiHandlerProfileInfo/MmiHandlerProfileInfo.inf
This change updated the override validation tags. It also integrates the cherry-pick commit from https://github.com/microsoft/mu_basecore/commit/4d722ac91608d3c4fbe807b418b77f2a6e279117.
For details on how to complete to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
This was tested on pipeline and passed override check. Also booted on Q35 branch.
The change needs to pair with basecore commit https://github.com/microsoft/mu_basecore/commit/4d722ac91608d3c4fbe807b418b77f2a6e279117 or later.
> Fix override from CodeQL and cherry-picks from latest basecore

- SeaPkg/Drivers/MsegSmramPei/MsegSmramPei.c
- SeaPkg/Drivers/MsegSmramPei/MsegSmramPei.inf
Uses `gEfiSmmSmramMemoryGuid` instead of `gEfiMmPeiMmramMemoryReserveGuid` since
this is used by most recent platforms and easier for platforms to support with
pre-existing code.
- Verified `gEfiSmmSmramMemoryGuid` is found and recreated with the MSEG range
successfully.
Use `gEfiSmmSmramMemoryGuid` as the MMRAM descriptor HOB to describe platform
MMRAM ranges.
> MsegSmramPei: Use gEfiSmmSmramMemoryGuid

- SeaPkg/Drivers/MsegSmramPei/MsegSmramPei.c
- SeaPkg/Drivers/MsegSmramPei/MsegSmramPei.inf
- SeaPkg/SeaPkg.dec
Produces a PPI that acts a signal to other code that MSEG has been configured. Platform code can optionally choose to act on the signal, for example, producing the MM Access PPI when MSEG has been identified.
Note: The PPI is produced unconditionally after MSEG identification has been attempted.
- Verified PPI is produced as expected
Use the PPI in a notification or DEPEX if helpful.
> SeaPkg/MsegSmramPei: Produce gMsegIdentifiedPpiGuid

- MmSupervisorPkg/Drivers/MmPeiLaunchers/MmIplPei.c
Currently the MmRanges reported through initialization steps will be manipulated by the IPL code to extend the last entry to be an empty placeholder so that it will be populated during the `ExecuteMmCoreFromMmram` routine.
However, the preemptively extended range will pull in extra data from the next hob, which could cause the rest of supervisor initialization to fault. This change fixed such issue by not overly copying data from hob.
For details on how to complete to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
This was tested on both QEMU Q35 and proprietary hardware platforms.
N/A
> Fixing MmRanges would pull in extra data from the next hob

- SeaPkg/Core/Init/StmInit.c
Should be `VOID **`.
- Compilation and boot
- N/A
> SeaPkg/StmInit: Fix cast type

- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.inf
Use track tags to BasePeCoffLib to support different versions of the library instance.
- CI build
- N/A
> SeaPkg/BasePeCoffNegativeLib: Use track tags

- SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
Includes MmSupervisorCore.aux to the Binaries directory so it is included in the release.
- Build and check `Binaries` directory content
- `Sea.inc.fdf` already referenced the file. This includes it in the NuGet package.
> SeaPkg/GenSeaArtifacts: Copy aux file to Binaries dir

- MmSupervisorPkg/Core/Handler/Mmi.c
- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Fixing an override hash failure from PiSmmCore
For details on how to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
This change was tested on Q35.
N/A
> Update override hash on PiSmmCore

- SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/lib.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/main.rs
Has the following updates to match the expected CBOR RIM format per multiple RFCs regarding CBOR.
1. Wraps The Protected header and payload in a byte string. What this means is that the protected header and payload are first cbor encoded into their respective final byte strings, then those byte strings are then further cbor encoded into the final byte string. This makes for an extra wrapper around the protected header and payload (The extra wrapper being a bytestring wrapper).
2. Converts the Signature to a byte string.
3. Converts the STM_BIN_GUID to a byte string.
4. Convert the digest values to a byte string
5. Convert the ConciseSwidTag payload to a map containing a single entry, 17, which is a list of the file measurements
Confirmed std parsing of the generated RIM works as expected …
> gen_rim: Multiple updates per CBOR rfc's

- MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
- SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
This change allows validation rules to only apply to certain build targets (DEBUG, RELEASE, NOOPT). By default, validation rules apply to all three, but a rule can be marked to only apply to a subset of them by adding a `target` field to the rule, which is a list of the supported targets.
Validated that no change to a config continues to apply all rules.
Validated that filtering a rule to a specific build target results in that rule being skipped in the final aux.
Add a `target = ['debug']`, `target = ['release']` or `target = ['noop']` or any combination there-of to any [[rule]] entry.
> gen_aux: Allow validation rules to only apply to certain build targets

- SeaPkg/Tools/GenSeaArtifacts/gen_rim/src/lib.rs
The previous iteration had the wrong byte order for encoding the UUID into the RIM. This PR reverses the byte order.
Verified through the C based RIM parser that the uuid is correct.
N/A
> gen_rim: Update uuid encoding byteorder

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/Drivers/MmSupervisorRing3Broker/MmSupervisorRing3Broker.inf
Update the override validation for StandaloneMmPkg changes that were cherry-picked from edk2.
No code changes are required, because the code changes were picked from a previous commit.
Local CI 
N/A
> Updated OverrideValidation hashes for new basecore

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
This auto generation ignores any symbols that are in code sections when auto generating a default configuration file for a particular PDB.
N/A
N/A
> Add ability to generate a dummy config file with all parsed symbols

- MmSupervisorPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
- MmSupervisorPkg/Docs/PlatformIntegration/SoftwareComponentOverview.md
- MmSupervisorPkg/Drivers/MmSupervisorRing3Performance/MmSupervisorRing3Performance.c
- MmSupervisorPkg/Drivers/MmSupervisorRing3Performance/MmSupervisorRing3Performance.inf
- MmSupervisorPkg/MmSupervisorPkg.dsc
Closes #383 
Adds a new `MM_STANDALONE` driver that is used to link against a
`PerformanceLib` core instance for MM user mode drivers.
An empty driver is reserved for this use case for the following
reasons:
1. Make integration and debug obvious and easy by having a clearly
named and designated driver for this purpose.
2. To be among the first MM user mode drivers dispatched to install
the performance protocol and make the performance service
available to other user mode drivers as early as possible.
3. To avoid linking directly to `MmSupervisorRing3Broker`. The MM
Core performance library instance code has functionality that
depends on MM services to be available. Since the Ring 3 Broker
is reponsible for initializing MM services in user mode, it is
complicated and error prone to attempt …
> MmSupervisorPkg: Add MmSupervisorRing3Performance

- SeaPkg/Core/Runtime/SeaResponderReport.c
- SeaPkg/Include/Library/PeCoffLibNegative.h
- SeaPkg/Include/Library/PeCoffValidationLib.h
- SeaPkg/Include/SeaAuxiliary.h
- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.inf
- SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
- SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.inf
- SeaPkg/Library/BasePeCoffValidationLib/Validation.c
- SeaPkg/SeaPkg.dec
- SeaPkg/SeaPkg.dsc
Breaks away the image validation into a standalone library, exposing the validation functions to be easily testable.
Passed the TestApp
Platforms will need to add `PeCoffValidationLib|SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.inf` to their DSC
> SeaPkg: Make Image Validation Testable

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/util.rs
Fixes the following bugs:
1. Incorrect padding by using min instead of max for calculating the loaded size of the section.
2. Incorrect priority of duplicate symbol names.
Applies the following enhancement:
1. Filter out symbols with empty name or 0x0 address.
Run on platform
N/A
> aux_gen: Fix bugs in tool

- SeaPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
- SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
Includes documentation on how to manually build the three binaries necessary to use SEA.
N/A
N/A
> SeaPkg: include manual build documentation.

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
Updates the raw data report with the following:
1. A new top level entry, sections, that contains a list of the PDB sections that are present in the PDB (and a single non-section section representing the PE Header).
2. Updates segments representing a symbol with the validation type of `ValidationType::None` to be considered covered rather than uncovered with the understanding that this covered reason is extremely weak.
Validated the json raw data output now contains the following:
```json
"sections": [
{
"name": "PE Header",
"start": "0x0",
"end": "0x1000"
},
{
"name": ".text",
"start": "0x1000",
"end": "0x28000"
},
{
"name": ".rdata",
"start": "0x28000",
"end": "0x37000"
},
...
]
```
Validated that "Validation Rule: None" types are now marked as covered
```json
{
"symbol": …
```
> gen_aux: raw data report updates

- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
- SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
- SeaPkg/Library/SmmCpuFeaturesLib/SmmStm.c
The pointer validation entry type has some issues with the validation logic.
1. It doesn't correctly increment with the entry list iteration leading to us point to nonvalid memory.
2. The calculation for the MSEG region was incorrect and was providing a random address for BASE and the incorrect number of CPU cores.
3. The target address was incorrectly being set to the location of symbol in the MM Supervisor image.  It has been updated to use the address of pointer so we can correctly judge if it's in or outside MSEG.
This changes address both of these issues by casting the entry type when incrementing to address (1) and then using the correct data structures to calculate the MSEG region.
Tested on Intel physical platform.  The validation process correctly gets MSEG.
N/A
> Fixed issues with the pointer validation code

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
Updates the coverage report generation to add symbol names to any segments that are missing coverage, if a symbol name exists. If multiple symbols exist for a single segment, the segment is split accordingly. symbols with only partial coverage (due to a rule using the offset / field config option) will now also show the symbol name for any portion of the symbol that is not covered.
Validated the following scenarios:
1. symbols names are added to uncovered sections
2. symbols that are partially covered due to a field rule will have all other parts of the symbol that are uncovered properly marked with the symbol name
3. a single segment marked as uncovered that contains multiple symbols properly shows the multiple symbols.
N/A
> cov_report: Add symbol names to segments missing coverage

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Changes the following configuration example:
``` toml
[[rule]]
symbol = "mysymbol"
validation.type = "content"
index = 3
[[rule]]
symbol = "mysymbol"
validation.type = "content"
array.index = 3
```
``` toml
#old
[[rule]]
symbol = "mysymbol"
validation.type = "content"
sentinel = true
#new
[[rule]]
symbol = "mysymbol"
validation.type = "content"
array.sentinel = true
```
Ensured invalid usage of the configuration results in an error.
Switch the following configuration values:
- `sentinel` -> `array.sentinel`
- `index` -> `array.index`
> gen_aux: Move array configuration to an 'array' parent

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Previously, if `index` was specified, then sentinel was required to be specified I did not indicate that the default value should be used if it is missing. This is fixed in this PR.
<_Describe the test(s) that were run to verify the changes._>
<_Describe how these changes should be integrated. Use N/A if nothing is required._>
> gen_aux: Provide default value for sentinel

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/util.rs
If `no_missing_rules = true` is in the configuration file, we abort the execution of the tool when we find a symbol in the pdb that does not have a corresponding rule in the same configuration file. This is to prevent a new symbol from being introduced in the binary without the maintainers knowing, so that they can create a new rule for this symbol.
This change updates this logic to be aware of the section that the symbol resides in, and only aborts execution if the missing symbol is in a section that is both `read` and `write`. Otherwise, the symbol is filtered out.
- Validated that removing a symbol from the configuration file that references a symbol in the `.data` section continues to result in a build error.
- Validated that removing a symbol from the configuration file that …
> gen_aux: Ignore symbols outside of read/write section

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/auxgen.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
While developing the coverage report raw data, it was noted that some spaces between symbols in the .data section were not associated with any symbols in the PDB. It was determined that this was padding in the symbols themselves which work to align them in the file. This pull request does the following things:
1. Cleans up the final build into multiple separate functions
2. Generates a content validation rule (of all zero) for any byte ranges not assocaited with a symbol
3. Generates a content validation rule (of all zeros) for any padding between sections, that is in a section that is both Read and Write.
<_Describe the test(s) that were run to verify the changes._>
<_Describe how these changes should be integrated. Use N/A if nothing is required._>
> aux_gen: Auto generate rules for padding

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/main.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/validation.rs
Disables the ability to put unexpected fields in top level fields the following tables: `[[KeySymbol]]`, `[[rule]]`, `[config]`, and the top level table of the file itself.
Validated that the file is properly parsed as is, and that putting miscellaneous data in these tables causes the parser to fail.
N/A
> gen_aux: Deny unknown config file fields

- SeaPkg/Include/Library/PeCoffValidationLib.h
- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
- SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
Update self ref validation to use the original image for validation.  This avoids the issue where the relocation code changes the target image contents that we're trying to validate leading to a failure in the rules validation.  Instead we use the original image to validate the pointer.
Tested on an Intel Physical platform.  The previously failing rules now pass.
N/A
> Update self ref validation to use the original image for validation

- MmSupervisorPkg/Core/Misc/MemoryAttributesTable.c
- SeaPkg/Core/Runtime/SeaResponderReport.c
- SeaPkg/Include/Library/PeCoffValidationLib.h
- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
- SeaPkg/Library/BasePeCoffValidationLib/BasePeCoffValidationLib.c
The read-only data section was never protected with the existing implementation.
This change adds the extra layer of protection to the read-only data section to prevent unintentional tampering.
The SEA validation routine is also updated to incorporate the memory attribute change.
This change was tested on QEMU Q35 virtual platform and passed test application.
N/A
> [Rebase & FF] Protect read-only data

- SeaPkg/Library/BasePeCoffLibNegative/BasePeCoffLibNegative.c
Add an image dump when encountering a validation error in BasePeCoffLibNegative.  This image can be used to debug what symbols are not being correctly validated.
Tested on an Intel physical platform.  The image is dumped as expected when a failure occurs.
N/A
> Add an image dump when encountering a validation error

- MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
MmSupervisorPkg: Update SysCall BaseLib hashes.
BaseLib was updated to include a new assembly file for MSVC AARCH64, no functional changes. 
Local CI to reproduced and verify override hash is correct. 
No integration necessary.
> MmSupervisorPkg: Update SysCall BaseLib hashes.

- SeaPkg/Tools/GenSeaArtifacts/test_aux/src/main.rs
Filters the generated rules to only those rules without a scope or with the specified scope. Previously, all rules were generated which would cause test-aux to fail for symbols that did not actually exist.
Validated that we continue to compile and rules are filtered when a scope exists that is not matched.
N/A
> test-aux: Add scope parameter for aux generation

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/Cargo.toml
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/config.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/metadata.rs
Adds a new rule, `guid`, that generates a `content` validation entry header in the aux file.
Validated that the generated aux file is the same exact file when replacing a content rule with the guid rule.
Consumers can now use `validation.type = "guid"` with a `guild` field of [a, b, c, [d0, d1, d2, d3, d4, d5, d6, d7]
```toml
[[rule]]
symbol = "MyGuid"
validation.type = "guid"
validation.content = [0x0, 0x0, 0x0, [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0]]
```
> aux_gen: Add new `guid` rule to `[[rule]]`

- SeaPkg/Tools/GenSeaArtifacts/gen_aux/Cargo.toml
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/readme.md
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/bin/create_config.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/config.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/metadata.rs
- SeaPkg/Tools/GenSeaArtifacts/gen_aux/src/report.rs
- SeaPkg/Tools/GenSeaArtifacts/test_aux/src/main.rs
Cherry-picks aux-gen commits from the `add_seapkg_pecoffneglib_core_cnt_2405` branch that do the following:
1. Updates `test-aux` tool to include a `--scope` argument, allowing the filtering of rules to be applied during aux generation.
2. Adds a `reviewed-by` field to the `[[rule]]` section of the aux gen configuration file.
3. Adds a `guid` validation type to the `[[rule]]` section of the aux gen configuration file.
4. Adds a `remarks` field to the `[[rule]]` section of the aux gen configuration file.
5. Adds a `last-reviewed` field to the `[[rule]]` section of the aux gen configuration file.
Local testing for each PR.
All new fields are optional, so no integration is necessary, though these new features can start to be used.
> [REBASE&FF] SeaPkg: Auxiliary file cherry-picks

- MmSupervisorPkg/Library/BaseLibSysCall/BaseLib.inf
We kept getting interrupted because unrelated changes from BaseLib. Untie the override tag here. We can update the missing functionality on a needed basis.
If possible, I think the real solution is to carry a few syscall call outs and the syscalllib in MdePkg.
Passing the CI.
N/A
> Remove override tag for BaseLib

- MmSupervisorPkg/MmSupervisorPkg.dsc
- SeaPkg/Core/Init/Paging.c
- SeaPkg/Core/Stm.h
- SeaPkg/Core/Stm.inf
- SeaPkg/SeaPkg.dsc
This change is meant to remove the direct reliance on PCI related content because the code in this repository does not use it directly, thus not introducing unneeded dependencies.
This is not a functional change.
N/A
> Remove PCI related content from this repository

- SeaPkg/Tools/GenSeaArtifacts/GenSeaArtifacts.py
This commit changes the input parameters of the different helper functions in GenSeaArtifacts.py to require more specific input paths, instead of assuming build directory structure. This allows for more flexibility in how the functions can be used, in scenarios where users wish to use these functions outside of the standard build process, or when multiple simultaneous builds of the same component cause the build directory structure to differ than normal.
Additionally, this commit removes the generate_sea_artifacts function as much of its functionality was outside the scope of this tool (specifically the copying of artifacts to specific directories outside of the caller's control). The useful parts of this functionality were moved to standalone helper functions (generate_test_aux_binary …
> GenSeaArtifacts.py: Make functions more customizable

- SeaPkg/Library/SmmCpuFeaturesLib/SmmStm.c
Right now, if MSEG is too small the error message gets buried behind an irrelevant message about not being able to find required SEA entries in present FVs:
```
MSEG too small.  Min MSEG Size = 00204000  Current MSEG Size = 00200000
StmHeader->SwStmHdr.StaticImageSize             = 0001D5A0
StmHeader->SwStmHdr.AdditionalDynamicMemorySize = 00146000
StmHeader->SwStmHdr.PerProcDynamicMemorySize    = 00008000
VMCS Size                                       = 00001000
Max CPUs                                        = 00000010
StmHeader->HwStmHdr.Cr3Offset                   = 0001E000
[DiscoverSmiEntryInFvHobs]   Failed to load SEA [E7F9ABC2-61A6-4AF3-A00F-1150CC6EFE20]
in FV at 0x6D7E4C98 of 6D7E4CAC bytes - Buffer Too Small.
[DiscoverSmiEntryInFvHobs] Found FV HOB referencing FV at …
```
> SmmCpuFeaturesLib: Tweak MSEG error handling logic

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- MmSupervisorPkg/MmSupervisorPkg.dec
Matches the current GitHub release version.
- CI
- No changes required. MM Supervisor version will be updated.
> Update MM Supervisor version to v19.000

- MmSupervisorPkg/Core/MmSupervisorCore.inf
- SeaPkg/MmiEntrySea/MmiEntrySea.inf
Override validation was tripped by a revert/reapply in mu_basecore's UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf
The functionality in PiSmmCpuDxeSmm was not changed (the revert was targeting MpInitLib, but the commit that was reverted/reapplied included changes in PiSmmCpuDxeSmm, causing a hash mismatch)
Local CI Build
Q35 booting.
No Integration necesary
> MmSupervisorPkg, SeaPkg: Update PiSmmCpuDxeSmm override hash
